name: alufluoride
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_custom_dropdown: ^3.1.1
  connectivity_plus: ^6.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.0.7
  injectable: ^2.3.5
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.1.0
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.14
  file_picker: 8.1.4
  url_launcher: ^6.3.1
  simple_barcode_scanner: ^0.3.0
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  pubspec_dependency_sorter: ^1.0.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

flutter_launcher_icons: 
  android: 'ic_launcher'
  image_path: 'assets/logo/alufluoride.png'
  remove_alpha_ios: true
  ios: true
  min_sdk_android: 21 

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
