// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'gate_entry_form.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$GateEntryFormImpl _$$GateEntryFormImplFromJson(Map<String, dynamic> json) =>
    _$GateEntryFormImpl(
      status: json['status'] as String?,
      name: json['name'] as String?,
      creationDate: json['creation'] as String? ?? '',
      plantName: json['plant_name'] as String?,
      entryType: json['gate_entry_type'] as String?,
      materialType: json['material_type'] as String?,
      supplierName: json['supplier_name'] as String?,
      entryTime: json['gate_entry_time'] as String?,
      customerName: json['customer_name'] as String?,
      supplierAddress: json['sender_address'] as String?,
      customerAddress: json['sender_address_copy'] as String?,
      expectedReturnDate: json['expected_return_date'] as String?,
      senderMobileNo: json['sender_mobile_no'] as String?,
      receiverName: json['receiver_name'] as String?,
      receiverDept: json['receiver_department'] as String?,
      receiverEmail: json['receiver_email'] as String?,
      receiverMobile: json['receiver_mobile_number'] as String?,
      poNumber: json['po_number'] as String?,
      isewayBill: (json['is_eway_bill'] as num?)?.toInt() ?? 0,
      ewayBill: json['eway_bill'] as String?,
      challanNumber: json['challan_number'] as String?,
      peopleCount: (json['people_count'] as num?)?.toInt(),
      vehicleType: json['vehicle_type'] as String?,
      vehicleNumber: json['vehicle_number'] as String?,
      driverName: json['driver_name'] as String?,
      drivermobileNo: json['driver_mobile_number'] as String?,
      weightSlipNo: json['weighment_slip_token_no'] as String?,
      weight: (json['weight__in_kgs_'] as num?)?.toDouble(),
      weighmentDate: json['weighment_date'] as String?,
      weighmentTime: json['weighment_time'] as String?,
      remarks: json['commentremark'] as String?,
      docStatus: (json['docstatus'] as num?)?.toInt(),
      senderName: json['sender_name'] as String?,
      driversLicensePhoto: json['drivers_license_photo'] as String?,
      vehicleImg: json['vehicle_image'] as String?,
      sealPhoto: json['seal_photo'] as String?,
      breathAnalyser: json['breath_analyser'] as String?,
      ocrScanning: json['invoicedc_image_ocr_scanning'] as String?,
      totalAmount: (json['total_amount'] as num?)?.toDouble(),
      licensePhotoImg: toNull(json['licensePhotoImg']),
      vehiclePhotoImg: toNull(json['vehiclePhotoImg']),
      sealPhotoImg: toNull(json['sealPhotoImg']),
      breathAnalyserImg: toNull(json['breathAnalyserImg']),
      invoiceImg:
          json['invoiceImg'] == null ? const [] : toNull(json['invoiceImg']),
    );

Map<String, dynamic> _$$GateEntryFormImplToJson(_$GateEntryFormImpl instance) =>
    <String, dynamic>{
      'status': instance.status,
      'name': instance.name,
      'creation': instance.creationDate,
      'plant_name': instance.plantName,
      'gate_entry_type': instance.entryType,
      'material_type': instance.materialType,
      'supplier_name': instance.supplierName,
      'gate_entry_time': instance.entryTime,
      'customer_name': instance.customerName,
      'sender_address': instance.supplierAddress,
      'sender_address_copy': instance.customerAddress,
      'expected_return_date': instance.expectedReturnDate,
      'sender_mobile_no': instance.senderMobileNo,
      'receiver_name': instance.receiverName,
      'receiver_department': instance.receiverDept,
      'receiver_email': instance.receiverEmail,
      'receiver_mobile_number': instance.receiverMobile,
      'po_number': instance.poNumber,
      'is_eway_bill': instance.isewayBill,
      'eway_bill': instance.ewayBill,
      'challan_number': instance.challanNumber,
      'people_count': instance.peopleCount,
      'vehicle_type': instance.vehicleType,
      'vehicle_number': instance.vehicleNumber,
      'driver_name': instance.driverName,
      'driver_mobile_number': instance.drivermobileNo,
      'weighment_slip_token_no': instance.weightSlipNo,
      'weight__in_kgs_': instance.weight,
      'weighment_date': instance.weighmentDate,
      'weighment_time': instance.weighmentTime,
      'commentremark': instance.remarks,
      'docstatus': instance.docStatus,
      'sender_name': instance.senderName,
      'drivers_license_photo': instance.driversLicensePhoto,
      'vehicle_image': instance.vehicleImg,
      'seal_photo': instance.sealPhoto,
      'breath_analyser': instance.breathAnalyser,
      'invoicedc_image_ocr_scanning': instance.ocrScanning,
      'total_amount': instance.totalAmount,
    };
