// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jK4QO6s2ofx-E6bEYSFviUhR64Cqgs8',
    appId: '1:97864712774:web:ac83b17e9151687f724047',
    messagingSenderId: '97864712774',
    projectId: 'alufluoride-8f2e1',
    authDomain: 'alufluoride-8f2e1.firebaseapp.com',
    storageBucket: 'alufluoride-8f2e1.firebasestorage.app',
    measurementId: 'G-PG85WNE22Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhqzFyZB0y4WTbRQK1BmyHmq-Eqdu6qp0',
    appId: '1:97864712774:android:c24a178e59b0b36e724047',
    messagingSenderId: '97864712774',
    projectId: 'alufluoride-8f2e1',
    storageBucket: 'alufluoride-8f2e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73qVMLfn1OntJgR9rJIbD1QKVbGZBd0Y',
    appId: '1:97864712774:ios:51419d04259d27f0724047',
    messagingSenderId: '97864712774',
    projectId: 'alufluoride-8f2e1',
    storageBucket: 'alufluoride-8f2e1.firebasestorage.app',
    iosBundleId: 'com.example.alufluoride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73qVMLfn1OntJgR9rJIbD1QKVbGZBd0Y',
    appId: '1:97864712774:ios:51419d04259d27f0724047',
    messagingSenderId: '97864712774',
    projectId: 'alufluoride-8f2e1',
    storageBucket: 'alufluoride-8f2e1.firebasestorage.app',
    iosBundleId: 'com.example.alufluoride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2jK4QO6s2ofx-E6bEYSFviUhR64Cqgs8',
    appId: '1:97864712774:web:003e2e5906318512724047',
    messagingSenderId: '97864712774',
    projectId: 'alufluoride-8f2e1',
    authDomain: 'alufluoride-8f2e1.firebaseapp.com',
    storageBucket: 'alufluoride-8f2e1.firebasestorage.app',
    measurementId: 'G-842GQKDTF3',
  );
}
