// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'gate_exit_form.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$GateExitFormImpl _$$GateExitFormImplFromJson(Map<String, dynamic> json) =>
    _$GateExitFormImpl(
      status: json['status'] as String?,
      name: json['name'] as String?,
      owner: json['owner'] as String?,
      creationDate: json['creation'] as String? ?? '',
      modifiedDate: json['modified'] as String?,
      modifiedBy: json['modified_by'] as String?,
      docstatus: (json['docstatus'] as num?)?.toInt(),
      exitTime: json['gate_exit_time'] as String?,
      plantName: json['plant_name'] as String?,
      exitType: json['gate_exit_type'] as String?,
      exitDate: json['gate_exit_date'] as String?,
      expectedReturnDate: json['expected_return_date'] as String?,
      senderEmployeeName: json['sender_employee_name'] as String?,
      senderEmployeeId: json['sender_employee_id'] as String?,
      senderEmail: json['sender_email'] as String?,
      senderMobileNo: json['sender_mobile_no'] as String?,
      gstin: json['gstin'] as String?,
      customerReceiverName: json['customerreceiver_name'] as String?,
      customerReceiverAddress: json['customerreceiver__address'] as String?,
      poNumber: json['po_number'] as String?,
      isewayBill: (json['is_eway_bill'] as num?)?.toInt(),
      ewayBill: json['eway_bill'] as String?,
      challanNumber: json['challan_number'] as String?,
      peopleCount: (json['people_count'] as num?)?.toInt() ?? 0,
      vehicleType: json['vehicle_type'] as String?,
      vehicleNumber: json['vehicle_number'] as String?,
      driverName: json['driver_name'] as String?,
      driverMobileNumber: json['driver_mobile_number'] as String?,
      weightSlipNo: json['weighment_slip_token_no'] as String?,
      weight: (json['weight__in_kgs_'] as num?)?.toDouble() ?? 0.0,
      weighmentDate: json['weighment_date'] as String?,
      weighmentTime: json['weighment_time'] as String?,
      licensePhoto: json['drivers_license_photo'] as String?,
      vehiclePhoto: json['vehicle_image'] as String?,
      sealPhoto: json['seal_photo'] as String?,
      breathAnalyser: json['breath_analyser'] as String?,
      invoice: json['invoicedc_image_ocr_scanning'] as String?,
      remarks: json['remark'] as String?,
      amendedFrom: json['amended_from'] as String?,
      totalAmount: (json['total_amount'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$GateExitFormImplToJson(_$GateExitFormImpl instance) =>
    <String, dynamic>{
      'status': instance.status,
      'name': instance.name,
      'owner': instance.owner,
      'creation': instance.creationDate,
      'modified': instance.modifiedDate,
      'modified_by': instance.modifiedBy,
      'docstatus': instance.docstatus,
      'gate_exit_time': instance.exitTime,
      'plant_name': instance.plantName,
      'gate_exit_type': instance.exitType,
      'gate_exit_date': instance.exitDate,
      'expected_return_date': instance.expectedReturnDate,
      'sender_employee_name': instance.senderEmployeeName,
      'sender_employee_id': instance.senderEmployeeId,
      'sender_email': instance.senderEmail,
      'sender_mobile_no': instance.senderMobileNo,
      'gstin': instance.gstin,
      'customerreceiver_name': instance.customerReceiverName,
      'customerreceiver__address': instance.customerReceiverAddress,
      'po_number': instance.poNumber,
      'is_eway_bill': instance.isewayBill,
      'eway_bill': instance.ewayBill,
      'challan_number': instance.challanNumber,
      'people_count': instance.peopleCount,
      'vehicle_type': instance.vehicleType,
      'vehicle_number': instance.vehicleNumber,
      'driver_name': instance.driverName,
      'driver_mobile_number': instance.driverMobileNumber,
      'weighment_slip_token_no': instance.weightSlipNo,
      'weight__in_kgs_': instance.weight,
      'weighment_date': instance.weighmentDate,
      'weighment_time': instance.weighmentTime,
      'drivers_license_photo': instance.licensePhoto,
      'vehicle_image': instance.vehiclePhoto,
      'seal_photo': instance.sealPhoto,
      'breath_analyser': instance.breathAnalyser,
      'invoicedc_image_ocr_scanning': instance.invoice,
      'remark': instance.remarks,
      'amended_from': instance.amendedFrom,
      'total_amount': instance.totalAmount,
    };
